version: "3.9"

services:
  service:
    build: ./WebService
    container_name: web-service
    ports:
      - "5234:80"

  client:
    build: ./WebClient
    container_name: web-client
    ports:
      - "5173:3000"

  database:
    build: ./WebData
    hostname: web-database
    container_name: web-database
    ports:
      - "1433:1433"
    volumes:
      - ./WebData:/mssql-data
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=@VeryComplexPassword1thTime
      - MSSQL_PID=developer

volumes:
  mssql-data: 
